server:
  port: 8085
spring:
  application:
    name: LBS-SERVICE
  redis:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    host: localhost
    port: 6379
